### PR TITLE
Add mgconsole build and release action 

### LINKED ISSUE #72: Add standalone mgconsole Docker container

### PR DESCRIPTION
**Pull request by antejavor**
PR adds CI action for building and releasing the mgconsole to a Docker Hub. 

This PR depends on this: https://github.com/memgraph/mgconsole/pull/78

Release note:
We have introduced a mgconsole Docker container(https://github.com/memgraph/mgconsole/pull/81)

TODO: 

- [x] Configure secrets on repo
- [x] [Write docs  ](https://github.com/memgraph/mgconsole/issues/83)

### CODE REVIEW

**Comment by MarkoBarisic** [comment]
2 comments:
1. Has this been tested?
2. You should add an input for overwriting existing image on dockerhub, it could prove useful in the future.

**Comment by antejavor** [comment]
1. Nope, I need permission to set up the secrets for the DockerHub. Will do it in the next commit, by test I assume publishing some 0.1 version just to see everything works?  
2. That means if I want to publish new image under the same version?

**Comment by MarkoBarisic** [comment]
1. Yeah, I'd suggest creating a test repo (mgconsole-test) under dockerhub, make it private, and try pushing to it by using this workflow.
2. Exactly

**Comment by MarkoBarisic** [comment]
I see the `DOCKER_USERNAME` and `DOCKER_PASSWORD` secrets are not set, they should be set within the `memgraph/mgconsole` repo

**Comment by antejavor** [comment]
CI action test on the test-repo: https://hub.docker.com/r/memgraph/mgconsole-test  cc @MarkoBarisic

**Comment by antejavor** [comment]
After the container is published in proper repo I will document things on docs, here and docker hub, related issue: https://github.com/memgraph/mgconsole/issues/83 

cc @MarkoBarisic

**Review by MarkoBarisic — APPROVED** [review]
LGTM

**Comment by gitbuda** [comment]
The closed message here is a bit misleading because we rebased `master` because some unwanted commits ended up in master, but this was merged to master.

**Pull request merged**
